// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package repository

import (
	"context"
)

// iteratorForInsertPollOptions implements pgx.CopyFromSource.
type iteratorForInsertPollOptions struct {
	rows                 []InsertPollOptionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertPollOptions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertPollOptions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].PollID,
		r.rows[0].Label,
	}, nil
}

func (r iteratorForInsertPollOptions) Err() error {
	return nil
}

// Insert poll options (used with UpdatePollOptions)
func (q *Queries) InsertPollOptions(ctx context.Context, arg []InsertPollOptionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"poll_option"}, []string{"poll_id", "label"}, &iteratorForInsertPollOptions{rows: arg})
}
