// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AppUser struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Poll struct {
	ID        uuid.UUID          `json:"id"`
	Question  string             `json:"question"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UserID    uuid.UUID          `json:"user_id"`
	Closed    bool               `json:"closed"`
}

type PollOption struct {
	ID        uuid.UUID          `json:"id"`
	PollID    uuid.UUID          `json:"poll_id"`
	Label     string             `json:"label"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Vote struct {
	ID        uuid.UUID          `json:"id"`
	PollID    uuid.UUID          `json:"poll_id"`
	UserID    uuid.UUID          `json:"user_id"`
	OptionID  uuid.UUID          `json:"option_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
