// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: vote.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createVote = `-- name: CreateVote :one
INSERT INTO votes (poll_id, user_id, option_id)
SELECT po.poll_id, $1, $2
FROM poll_option po
JOIN poll p ON p.id = po.poll_id
WHERE po.id = $2
  AND p.closed = FALSE
ON CONFLICT (poll_id, user_id) DO UPDATE
SET option_id = EXCLUDED.option_id
WHERE EXISTS (
  SELECT 1
  FROM poll p
  WHERE p.id = EXCLUDED.poll_id
    AND p.closed = FALSE
)
RETURNING id, poll_id
`

type CreateVoteParams struct {
	UserID   uuid.UUID `json:"user_id"`
	OptionID uuid.UUID `json:"option_id"`
}

type CreateVoteRow struct {
	ID     uuid.UUID `json:"id"`
	PollID uuid.UUID `json:"poll_id"`
}

// also block the UPDATE path if the poll is closed
func (q *Queries) CreateVote(ctx context.Context, arg CreateVoteParams) (CreateVoteRow, error) {
	row := q.db.QueryRow(ctx, createVote, arg.UserID, arg.OptionID)
	var i CreateVoteRow
	err := row.Scan(&i.ID, &i.PollID)
	return i, err
}

const getUserOptionIdByPollId = `-- name: GetUserOptionIdByPollId :one
SELECT option_id FROM votes WHERE poll_id = $1 AND user_id = $2
`

type GetUserOptionIdByPollIdParams struct {
	PollID uuid.UUID `json:"poll_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetUserOptionIdByPollId(ctx context.Context, arg GetUserOptionIdByPollIdParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserOptionIdByPollId, arg.PollID, arg.UserID)
	var option_id uuid.UUID
	err := row.Scan(&option_id)
	return option_id, err
}

const getVoteById = `-- name: GetVoteById :one
SELECT id, poll_id, user_id, option_id, created_at FROM votes WHERE id = $1
`

func (q *Queries) GetVoteById(ctx context.Context, id uuid.UUID) (Vote, error) {
	row := q.db.QueryRow(ctx, getVoteById, id)
	var i Vote
	err := row.Scan(
		&i.ID,
		&i.PollID,
		&i.UserID,
		&i.OptionID,
		&i.CreatedAt,
	)
	return i, err
}

const listVotesByPollId = `-- name: ListVotesByPollId :many
SELECT option_id, COUNT(*) AS vote_count
FROM votes
WHERE poll_id = $1
GROUP BY option_id
`

type ListVotesByPollIdRow struct {
	OptionID  uuid.UUID `json:"option_id"`
	VoteCount int64     `json:"vote_count"`
}

func (q *Queries) ListVotesByPollId(ctx context.Context, pollID uuid.UUID) ([]ListVotesByPollIdRow, error) {
	rows, err := q.db.Query(ctx, listVotesByPollId, pollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVotesByPollIdRow
	for rows.Next() {
		var i ListVotesByPollIdRow
		if err := rows.Scan(&i.OptionID, &i.VoteCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
